export const PREDEFINED_CROPS = [
  "Rice (Paddy)",
  "Wheat",
  "Maize",
  "Cotton",
  "Sugarcane",
  "Soybean",
  "Groundnut",
  "Mustard",
  "Sunflower",
  "Jowar (Sorghum)",
  "Bajra (Pearl Millet)",
  "Ragi (Finger Millet)",
  "Barley",
  "Gram (Chickpea)",
  "Tur/Arhar (Pigeon Pea)",
  "Moong (Green Gram)",
  "Urad (Black Gram)",
  "Masoor (Lentil)",
  "Potato",
  "Tomato",
  "Onion",
  "Chilli",
  "Brinjal (Eggplant)",
  "Okra (Bhindi)",
  "Cauliflower",
  "Cabbage",
  "Peas",
  "Beans",
  "Cucumber",
  "Bitter Gourd",
  "Bottle Gourd",
  "Watermelon",
  "Mango",
  "Banana",
  "Grapes",
  "Pomegranate",
  "Citrus (Orange/Lime)",
  "Apple",
  "Papaya",
  "Guava",
  "Tea",
  "Coffee",
  "Coconut",
  "Arecanut",
  "Rubber",
  "Jute",
  "Tobacco",
  "Turmeric",
  "Ginger",
  "Cardamom",
];
